
CREATE TABLE languages (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL
);

CREATE TABLE publishers (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    address VARCHAR2(255),
    contact_email VARCHAR2(100)
);

CREATE TABLE categories (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    parent_id NUMBER,
    CONSTRAINT fk_category_parent FOREIGN KEY (parent_id) REFERENCES categories(id)
);

CREATE TABLE authors (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    bio CLOB
);

CREATE TABLE books (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(200) NOT NULL,
    isbn VARCHAR2(20),
    edition VARCHAR2(50),
    publication_year NUMBER,
    summary CLOB,
    cover_image_url VARCHAR2(255),
    language_id NUMBER,
    publisher_id NUMBER,
    CONSTRAINT fk_books_language FOREIGN KEY (language_id) REFERENCES languages(id),
    CONSTRAINT fk_books_publisher FOREIGN KEY (publisher_id) REFERENCES publishers(id)
);

CREATE TABLE book_authors (
    book_id NUMBER,
    author_id NUMBER,
    PRIMARY KEY (book_id, author_id),
    FOREIGN KEY (book_id) REFERENCES books(id),
    FOREIGN KEY (author_id) REFERENCES authors(id)
);

CREATE TABLE book_categories (
    book_id NUMBER,
    category_id NUMBER,
    PRIMARY KEY (book_id, category_id),
    FOREIGN KEY (book_id) REFERENCES books(id),
    FOREIGN KEY (category_id) REFERENCES categories(id)
);

CREATE TABLE members (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    email VARCHAR2(100),
    phone VARCHAR2(20),
    address VARCHAR2(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(100) UNIQUE NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    password VARCHAR2(255) NOT NULL,
    is_active NUMBER(1) DEFAULT 1, -- 1 = true, 0 = false
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


Create TABLE roles (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	 name VARCHAR2(100) NOT NULL

)

CREATE TABLE users_roles (
    user_id NUMBER,
    role_id NUMBER,
    PRIMARY KEY (user_id, role_id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (role_id) REFERENCES roles(id)
);

CREATE TABLE borrowings (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id NUMBER NOT NULL,
    book_id NUMBER NOT NULL,
    borrow_date DATE,
    due_date DATE,
    return_date DATE,
    status VARCHAR2(20),
    CONSTRAINT fk_borrowings_member FOREIGN KEY (member_id) REFERENCES members(id),
    CONSTRAINT fk_borrowings_book FOREIGN KEY (book_id) REFERENCES books(id)
);

CREATE TABLE user_log (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2 NOT NULL,
    ip_address VARCHAR2 NOT NULL,
    action_type VARCHAR2 NOT NULL,
    details VARCHAR2 NOT NULL,
    action_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP

)
